spring.application.name=Screenmatch

spring.datasource.url=jdbc:postgresql://localhost:5432/screenmatch
spring.datasource.username=postgres
spring.datasource.password=iggor051
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Atualizar a tabela no banco de dados
spring.jpa.hibernate.ddl-auto=update
